org.gradle.jvmargs=-Xmx1g

# Project coordinates
group=com.idre
version=1.0.0-SNAPSHOT

# Java and framework versions
javaVersion=21

springBootVersion=3.5.0
springDependencyManagementVersion=1.1.7

springCloudVersion=2025.0.0

# Library versions
lombokVersion=1.18.38
mapstructVersion=1.6.3

postgresVersion=42.7.7

openApiVersion=2.8.9
